version: '3.8'

services:
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  producer:
    container_name: producer
    build: 
      context: ./Producer
      dockerfile: Dockerfile
    volumes:
      - ./Data:/app/Data
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  
  consumer:
    container_name: csharp_consumer
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbit
      - ELASTIC_URI=http://elasticsearch:9200
  

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  es_data: